### ISSUE TITLE
Clicking on the Patient Name in the Patient header links to the clinician facing patient dashboard

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/intelehealth-openmrs-module#40] opened 2017-08-11 15:35 UTC

**Comment by nehagoel2** [comment] 2017-11-14 21:00
"Clinician facing patient dashboard" == Page from the Ref App.

**Comment by nehagoel2** [comment] 2017-11-23 05:24
https://github.com/openmrs/openmrs-module-coreapps/blob/master/omod/src/main/webapp/fragments/patientHeader.gsp

**Comment by nehagoel2** [comment] 2017-11-30 04:23
You need to overload the following variables in to redirect the url to the Intelehealth patient dashboard - contextPath and config.dashboardUrl

See
        jq(".demographics .name").click(function () {
            emr.navigateTo({
                url: "${ ui.urlBind("/" + contextPath + config.dashboardUrl, [ patientId: patient.patient.id ] ) }"
            });
        })


https://github.com/openmrs/openmrs-module-coreapps/blob/master/omod/src/main/webapp/fragments/patientHeader.gsp

**Comment by AniketIntelhealth** [comment] 2017-12-05 15:36
@neha @amalafrozalam this is regarding issue no #40.  i did some research and came to the conclusion that while overriding the default core apps url we can solve this issue. but the problem is  when overrided with intelehealth dashboard url with the default value its not working. can any 1 help me here out?
also there is something called model.add attribute property in intelehealth dashboardurl.gsp page which is responsible for adding core apps default url.

**Comment by AniketIntelhealth** [comment] 2017-12-05 15:37
![screenshot from 2017-12-05 12-13-07](https://user-images.githubusercontent.com/33891378/33615511-5a6a59b4-da00-11e7-97ca-8c66fb348fd3.png)

**Comment by AniketIntelhealth** [comment] 2017-12-06 10:54
@amalafrozalam in  intelehealthPatientDashboard.gsp there is fragment called
${ ui.includeFragment("coreapps", "patientHeader", [ patient: patient.patient, activeVisit: activeVisit, appContextModel: appContextModel ]) }

which is responsible for routing to core app url.
if we can replace this url with "openmrs/intelehealth/intelehealthPatientDashboard.page?patientId=" + v.visit.patient.uuid, v.visit.patient) }" this fragment. the issue can be solved .

**Comment by nehagoel2** [comment] 2017-12-08 03:29
@prithi69 can you test this?

**Comment by AniketIntelhealth** [comment] 2017-12-08 03:41
http://localhost:8081/openmrs/admin/maintenance/globalProps.form

**Comment by AniketIntelhealth** [comment] 2017-12-08 07:33
https://talk.openmrs.org/t/privilege-to-edit-patient-demographic-information/11520 @neha can you go through the link and help me out what "darius" wants to say

**Comment by nehagoel2** [comment] 2017-12-08 08:05
So it looks like someone else also wanted this feature. But per Darius's comment, this functionality does not exist.

**Comment by prithi69** [comment] 2017-12-08 17:23
patient header links to clinician dashboard, not our inteleealth dashboard.

**Comment by AniketIntelhealth** [comment] 2017-12-11 05:32
so what can be done for sure is to add your own extension through your custom module, the same way the Registration App module does it And then, to make sure that your custom extension is being picked up, you could disable the “default” one (=the one defined by the Reg. App module) through your custom module’s activator. With something like that:

AppFrameworkService service = Context.getService(AppFrameworkService.class);
service.disableExtension("org.openmrs.module.registrationapp.editPatientDemographics");


--Dimitri's words on changing the edit button on patient Dashboard

**Comment by AniketIntelhealth** [comment] 2017-12-11 13:02
![screenshot from 2017-12-11 17-50-33](https://user-images.githubusercontent.com/33891378/33832217-463ec808-dea1-11e7-8dcd-b20fe344fcfc.png)
@nehagoel2  @amalafrozalam  i made a  patientHeader.gsp file with a controller called PatientHeaderFragmentController.java but when i replace the coreapp fragment with created fragment it gives the above error any help?

**Comment by prithi69** [comment] 2018-01-04 09:51
Patient Header is been disabled, but edit button still persist. So we may close the issue.

**Closed** 2018-01-04 09:51 UTC
Labels: priority:medium
